
package com.example.webSpring.api.core.security;

public enum ResourceType {
    SYSTEM_USER_MANAGEMENT,
    ROLE_MANAGEMENT,
    MENU_MANAGEMENT,
    ROLE_MENU,
    ROLE_PERMISSION,
    ON_BOARDING_MANAGEMENT,
    USER_SUBSCRIPTION_MANAGEMENT,
    COM_CAT_MANAGEMENT,
    COM_CAT_TYPE_MANAGEMENT,
    END_USER_MANAGEMENT,
    AUDIT_LOGS,
    SNAP_SHOTS,
    TELCO_SUB_MANAGEMENT,
    DEVICE_PUSH_NOTIFICATION,
    SYSTEM_DEVICE_MANAGEMENT,
    USER_VERIFICATION_REQUEST,
    SYSTEM_LANGUAGE_MANAGEMENT,
    SURVEY_MANAGEMENT,
    // Authorities Resource Type
    AUTHORITIES_USER_MANAGEMENT,
    AUTHORITY_TENANT_MANAGEMENT,
    AUTHORITIES_DEPARTMENT_MANAGEMENT,
    AUTHORITIES_COM_CAT_MANAGEMENT,
    AUTHORITIES_COM_CAT_TYPE_MANAGEMENT,
    AUTHORITIES_FACILITY_MANAGEMENT,
    AUTHORITIES_ROLE_MANAGEMENT,
    AUTHORITIES_DEVICE_MONITORING_MANAGEMENT,
}
